// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events_api/events.proto

package events_api

import (
	models "github.com/sashapremium/events/events/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserHash      string                 `protobuf:"bytes,2,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_events_api_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_api_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_events_api_events_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPostRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *models.PostModel      `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_events_api_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_api_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_events_api_events_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostResponse) GetPost() *models.PostModel {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *GetPostResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserHash      string                 `protobuf:"bytes,2,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_events_api_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_api_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_events_api_events_proto_rawDescGZIP(), []int{2}
}

func (x *LikePostRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LikePostRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

type LikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostResponse) Reset() {
	*x = LikePostResponse{}
	mi := &file_events_api_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostResponse) ProtoMessage() {}

func (x *LikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_api_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostResponse.ProtoReflect.Descriptor instead.
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return file_events_api_events_proto_rawDescGZIP(), []int{3}
}

func (x *LikePostResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RepostPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserHash      string                 `protobuf:"bytes,2,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepostPostRequest) Reset() {
	*x = RepostPostRequest{}
	mi := &file_events_api_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepostPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostPostRequest) ProtoMessage() {}

func (x *RepostPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_api_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostPostRequest.ProtoReflect.Descriptor instead.
func (*RepostPostRequest) Descriptor() ([]byte, []int) {
	return file_events_api_events_proto_rawDescGZIP(), []int{4}
}

func (x *RepostPostRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RepostPostRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

type RepostPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepostPostResponse) Reset() {
	*x = RepostPostResponse{}
	mi := &file_events_api_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepostPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostPostResponse) ProtoMessage() {}

func (x *RepostPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_api_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostPostResponse.ProtoReflect.Descriptor instead.
func (*RepostPostResponse) Descriptor() ([]byte, []int) {
	return file_events_api_events_proto_rawDescGZIP(), []int{5}
}

func (x *RepostPostResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserHash      string                 `protobuf:"bytes,2,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_events_api_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_api_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_events_api_events_proto_rawDescGZIP(), []int{6}
}

func (x *AddCommentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddCommentRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *AddCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AddCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *models.CommentModel   `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_events_api_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_api_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_events_api_events_proto_rawDescGZIP(), []int{7}
}

func (x *AddCommentResponse) GetComment() *models.CommentModel {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *AddCommentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_events_api_events_proto protoreflect.FileDescriptor

const file_events_api_events_proto_rawDesc = "" +
	"\n" +
	"\x17events_api/events.proto\x12\x12content.service.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x19models/events_model.proto\"=\n" +
	"\x0eGetPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tuser_hash\x18\x02 \x01(\tR\buserHash\"[\n" +
	"\x0fGetPostResponse\x120\n" +
	"\x04post\x18\x01 \x01(\v2\x1c.content.models.v1.PostModelR\x04post\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\">\n" +
	"\x0fLikePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tuser_hash\x18\x02 \x01(\tR\buserHash\"*\n" +
	"\x10LikePostResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"@\n" +
	"\x11RepostPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tuser_hash\x18\x02 \x01(\tR\buserHash\",\n" +
	"\x12RepostPostResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"T\n" +
	"\x11AddCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tuser_hash\x18\x02 \x01(\tR\buserHash\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"g\n" +
	"\x12AddCommentResponse\x129\n" +
	"\acomment\x18\x01 \x01(\v2\x1f.content.models.v1.CommentModelR\acomment\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xff\x03\n" +
	"\rEventsService\x12m\n" +
	"\aGetPost\x12\".content.service.v2.GetPostRequest\x1a#.content.service.v2.GetPostResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/post/{id}\x12x\n" +
	"\bLikePost\x12#.content.service.v2.LikePostRequest\x1a$.content.service.v2.LikePostResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/post/{id}/like\x12\x80\x01\n" +
	"\n" +
	"RepostPost\x12%.content.service.v2.RepostPostRequest\x1a&.content.service.v2.RepostPostResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/post/{id}/repost\x12\x81\x01\n" +
	"\n" +
	"AddComment\x12%.content.service.v2.AddCommentRequest\x1a&.content.service.v2.AddCommentResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/post/{id}/commentBIZGgithub.com/sashapremium/events/events/internal/pb/events_api;events_apib\x06proto3"

var (
	file_events_api_events_proto_rawDescOnce sync.Once
	file_events_api_events_proto_rawDescData []byte
)

func file_events_api_events_proto_rawDescGZIP() []byte {
	file_events_api_events_proto_rawDescOnce.Do(func() {
		file_events_api_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_api_events_proto_rawDesc), len(file_events_api_events_proto_rawDesc)))
	})
	return file_events_api_events_proto_rawDescData
}

var file_events_api_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_events_api_events_proto_goTypes = []any{
	(*GetPostRequest)(nil),      // 0: content.service.v2.GetPostRequest
	(*GetPostResponse)(nil),     // 1: content.service.v2.GetPostResponse
	(*LikePostRequest)(nil),     // 2: content.service.v2.LikePostRequest
	(*LikePostResponse)(nil),    // 3: content.service.v2.LikePostResponse
	(*RepostPostRequest)(nil),   // 4: content.service.v2.RepostPostRequest
	(*RepostPostResponse)(nil),  // 5: content.service.v2.RepostPostResponse
	(*AddCommentRequest)(nil),   // 6: content.service.v2.AddCommentRequest
	(*AddCommentResponse)(nil),  // 7: content.service.v2.AddCommentResponse
	(*models.PostModel)(nil),    // 8: content.models.v1.PostModel
	(*models.CommentModel)(nil), // 9: content.models.v1.CommentModel
}
var file_events_api_events_proto_depIdxs = []int32{
	8, // 0: content.service.v2.GetPostResponse.post:type_name -> content.models.v1.PostModel
	9, // 1: content.service.v2.AddCommentResponse.comment:type_name -> content.models.v1.CommentModel
	0, // 2: content.service.v2.EventsService.GetPost:input_type -> content.service.v2.GetPostRequest
	2, // 3: content.service.v2.EventsService.LikePost:input_type -> content.service.v2.LikePostRequest
	4, // 4: content.service.v2.EventsService.RepostPost:input_type -> content.service.v2.RepostPostRequest
	6, // 5: content.service.v2.EventsService.AddComment:input_type -> content.service.v2.AddCommentRequest
	1, // 6: content.service.v2.EventsService.GetPost:output_type -> content.service.v2.GetPostResponse
	3, // 7: content.service.v2.EventsService.LikePost:output_type -> content.service.v2.LikePostResponse
	5, // 8: content.service.v2.EventsService.RepostPost:output_type -> content.service.v2.RepostPostResponse
	7, // 9: content.service.v2.EventsService.AddComment:output_type -> content.service.v2.AddCommentResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_events_api_events_proto_init() }
func file_events_api_events_proto_init() {
	if File_events_api_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_api_events_proto_rawDesc), len(file_events_api_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_api_events_proto_goTypes,
		DependencyIndexes: file_events_api_events_proto_depIdxs,
		MessageInfos:      file_events_api_events_proto_msgTypes,
	}.Build()
	File_events_api_events_proto = out.File
	file_events_api_events_proto_goTypes = nil
	file_events_api_events_proto_depIdxs = nil
}
