// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: models/events_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostModel) Reset() {
	*x = PostModel{}
	mi := &file_models_events_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostModel) ProtoMessage() {}

func (x *PostModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_events_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostModel.ProtoReflect.Descriptor instead.
func (*PostModel) Descriptor() ([]byte, []int) {
	return file_models_events_model_proto_rawDescGZIP(), []int{0}
}

func (x *PostModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostModel) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *PostModel) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PostModel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostModel) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type CommentModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserHash      string                 `protobuf:"bytes,3,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentModel) Reset() {
	*x = CommentModel{}
	mi := &file_models_events_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentModel) ProtoMessage() {}

func (x *CommentModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_events_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentModel.ProtoReflect.Descriptor instead.
func (*CommentModel) Descriptor() ([]byte, []int) {
	return file_models_events_model_proto_rawDescGZIP(), []int{1}
}

func (x *CommentModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentModel) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentModel) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *CommentModel) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CommentModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_models_events_model_proto protoreflect.FileDescriptor

const file_models_events_model_proto_rawDesc = "" +
	"\n" +
	"\x19models/events_model.proto\x12\x11content.models.v1\"\xa7\x01\n" +
	"\tPostModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12!\n" +
	"\fpublished_at\x18\x06 \x01(\tR\vpublishedAt\"\x87\x01\n" +
	"\fCommentModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x04R\x06postId\x12\x1b\n" +
	"\tuser_hash\x18\x03 \x01(\tR\buserHash\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAtB:Z8github.com/sashapremium/events/internal/pb/models;modelsb\x06proto3"

var (
	file_models_events_model_proto_rawDescOnce sync.Once
	file_models_events_model_proto_rawDescData []byte
)

func file_models_events_model_proto_rawDescGZIP() []byte {
	file_models_events_model_proto_rawDescOnce.Do(func() {
		file_models_events_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_events_model_proto_rawDesc), len(file_models_events_model_proto_rawDesc)))
	})
	return file_models_events_model_proto_rawDescData
}

var file_models_events_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_events_model_proto_goTypes = []any{
	(*PostModel)(nil),    // 0: content.models.v1.PostModel
	(*CommentModel)(nil), // 1: content.models.v1.CommentModel
}
var file_models_events_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_events_model_proto_init() }
func file_models_events_model_proto_init() {
	if File_models_events_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_events_model_proto_rawDesc), len(file_models_events_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_events_model_proto_goTypes,
		DependencyIndexes: file_models_events_model_proto_depIdxs,
		MessageInfos:      file_models_events_model_proto_msgTypes,
	}.Build()
	File_models_events_model_proto = out.File
	file_models_events_model_proto_goTypes = nil
	file_models_events_model_proto_depIdxs = nil
}
