// Code generated by mockery v2.53.5. DO NOT EDIT.

package analyticsService

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// AddUniqueUser provides a mock function with given fields: ctx, postID, userHash
func (_m *MockCache) AddUniqueUser(ctx context.Context, postID uint64, userHash string) (bool, error) {
	ret := _m.Called(ctx, postID, userHash)

	if len(ret) == 0 {
		panic("no return value specified for AddUniqueUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) (bool, error)); ok {
		return rf(ctx, postID, userHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) bool); ok {
		r0 = rf(ctx, postID, userHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = rf(ctx, postID, userHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_AddUniqueUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUniqueUser'
type MockCache_AddUniqueUser_Call struct {
	*mock.Call
}

// AddUniqueUser is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint64
//   - userHash string
func (_e *MockCache_Expecter) AddUniqueUser(ctx interface{}, postID interface{}, userHash interface{}) *MockCache_AddUniqueUser_Call {
	return &MockCache_AddUniqueUser_Call{Call: _e.mock.On("AddUniqueUser", ctx, postID, userHash)}
}

func (_c *MockCache_AddUniqueUser_Call) Run(run func(ctx context.Context, postID uint64, userHash string)) *MockCache_AddUniqueUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(string))
	})
	return _c
}

func (_c *MockCache_AddUniqueUser_Call) Return(_a0 bool, _a1 error) *MockCache_AddUniqueUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_AddUniqueUser_Call) RunAndReturn(run func(context.Context, uint64, string) (bool, error)) *MockCache_AddUniqueUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetDelta provides a mock function with given fields: ctx, postID
func (_m *MockCache) GetDelta(ctx context.Context, postID uint64) (TotalsDelta, bool, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetDelta")
	}

	var r0 TotalsDelta
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (TotalsDelta, bool, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) TotalsDelta); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(TotalsDelta)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) bool); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = rf(ctx, postID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCache_GetDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDelta'
type MockCache_GetDelta_Call struct {
	*mock.Call
}

// GetDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint64
func (_e *MockCache_Expecter) GetDelta(ctx interface{}, postID interface{}) *MockCache_GetDelta_Call {
	return &MockCache_GetDelta_Call{Call: _e.mock.On("GetDelta", ctx, postID)}
}

func (_c *MockCache_GetDelta_Call) Run(run func(ctx context.Context, postID uint64)) *MockCache_GetDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCache_GetDelta_Call) Return(_a0 TotalsDelta, _a1 bool, _a2 error) *MockCache_GetDelta_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCache_GetDelta_Call) RunAndReturn(run func(context.Context, uint64) (TotalsDelta, bool, error)) *MockCache_GetDelta_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirtyBatch provides a mock function with given fields: ctx, limit
func (_m *MockCache) GetDirtyBatch(ctx context.Context, limit int) ([]uint64, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetDirtyBatch")
	}

	var r0 []uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]uint64, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []uint64); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_GetDirtyBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirtyBatch'
type MockCache_GetDirtyBatch_Call struct {
	*mock.Call
}

// GetDirtyBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockCache_Expecter) GetDirtyBatch(ctx interface{}, limit interface{}) *MockCache_GetDirtyBatch_Call {
	return &MockCache_GetDirtyBatch_Call{Call: _e.mock.On("GetDirtyBatch", ctx, limit)}
}

func (_c *MockCache_GetDirtyBatch_Call) Run(run func(ctx context.Context, limit int)) *MockCache_GetDirtyBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCache_GetDirtyBatch_Call) Return(_a0 []uint64, _a1 error) *MockCache_GetDirtyBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_GetDirtyBatch_Call) RunAndReturn(run func(context.Context, int) ([]uint64, error)) *MockCache_GetDirtyBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastSyncedAt provides a mock function with given fields: ctx
func (_m *MockCache) GetLastSyncedAt(ctx context.Context) (string, bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastSyncedAt")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCache_GetLastSyncedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastSyncedAt'
type MockCache_GetLastSyncedAt_Call struct {
	*mock.Call
}

// GetLastSyncedAt is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCache_Expecter) GetLastSyncedAt(ctx interface{}) *MockCache_GetLastSyncedAt_Call {
	return &MockCache_GetLastSyncedAt_Call{Call: _e.mock.On("GetLastSyncedAt", ctx)}
}

func (_c *MockCache_GetLastSyncedAt_Call) Run(run func(ctx context.Context)) *MockCache_GetLastSyncedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCache_GetLastSyncedAt_Call) Return(_a0 string, _a1 bool, _a2 error) *MockCache_GetLastSyncedAt_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCache_GetLastSyncedAt_Call) RunAndReturn(run func(context.Context) (string, bool, error)) *MockCache_GetLastSyncedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetTop provides a mock function with given fields: ctx, metric, limit
func (_m *MockCache) GetTop(ctx context.Context, metric string, limit uint32) ([]TopItem, error) {
	ret := _m.Called(ctx, metric, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTop")
	}

	var r0 []TopItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32) ([]TopItem, error)); ok {
		return rf(ctx, metric, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32) []TopItem); ok {
		r0 = rf(ctx, metric, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TopItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint32) error); ok {
		r1 = rf(ctx, metric, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_GetTop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTop'
type MockCache_GetTop_Call struct {
	*mock.Call
}

// GetTop is a helper method to define mock.On call
//   - ctx context.Context
//   - metric string
//   - limit uint32
func (_e *MockCache_Expecter) GetTop(ctx interface{}, metric interface{}, limit interface{}) *MockCache_GetTop_Call {
	return &MockCache_GetTop_Call{Call: _e.mock.On("GetTop", ctx, metric, limit)}
}

func (_c *MockCache_GetTop_Call) Run(run func(ctx context.Context, metric string, limit uint32)) *MockCache_GetTop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint32))
	})
	return _c
}

func (_c *MockCache_GetTop_Call) Return(_a0 []TopItem, _a1 error) *MockCache_GetTop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_GetTop_Call) RunAndReturn(run func(context.Context, string, uint32) ([]TopItem, error)) *MockCache_GetTop_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotals provides a mock function with given fields: ctx, postID
func (_m *MockCache) GetTotals(ctx context.Context, postID uint64) (PostTotals, bool, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotals")
	}

	var r0 PostTotals
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (PostTotals, bool, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) PostTotals); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(PostTotals)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) bool); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = rf(ctx, postID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCache_GetTotals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotals'
type MockCache_GetTotals_Call struct {
	*mock.Call
}

// GetTotals is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint64
func (_e *MockCache_Expecter) GetTotals(ctx interface{}, postID interface{}) *MockCache_GetTotals_Call {
	return &MockCache_GetTotals_Call{Call: _e.mock.On("GetTotals", ctx, postID)}
}

func (_c *MockCache_GetTotals_Call) Run(run func(ctx context.Context, postID uint64)) *MockCache_GetTotals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCache_GetTotals_Call) Return(_a0 PostTotals, _a1 bool, _a2 error) *MockCache_GetTotals_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCache_GetTotals_Call) RunAndReturn(run func(context.Context, uint64) (PostTotals, bool, error)) *MockCache_GetTotals_Call {
	_c.Call.Return(run)
	return _c
}

// IncrTop provides a mock function with given fields: ctx, metric, postID, inc
func (_m *MockCache) IncrTop(ctx context.Context, metric string, postID uint64, inc int64) error {
	ret := _m.Called(ctx, metric, postID, inc)

	if len(ret) == 0 {
		panic("no return value specified for IncrTop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, int64) error); ok {
		r0 = rf(ctx, metric, postID, inc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_IncrTop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrTop'
type MockCache_IncrTop_Call struct {
	*mock.Call
}

// IncrTop is a helper method to define mock.On call
//   - ctx context.Context
//   - metric string
//   - postID uint64
//   - inc int64
func (_e *MockCache_Expecter) IncrTop(ctx interface{}, metric interface{}, postID interface{}, inc interface{}) *MockCache_IncrTop_Call {
	return &MockCache_IncrTop_Call{Call: _e.mock.On("IncrTop", ctx, metric, postID, inc)}
}

func (_c *MockCache_IncrTop_Call) Run(run func(ctx context.Context, metric string, postID uint64, inc int64)) *MockCache_IncrTop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint64), args[3].(int64))
	})
	return _c
}

func (_c *MockCache_IncrTop_Call) Return(_a0 error) *MockCache_IncrTop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_IncrTop_Call) RunAndReturn(run func(context.Context, string, uint64, int64) error) *MockCache_IncrTop_Call {
	_c.Call.Return(run)
	return _c
}

// IncrTotals provides a mock function with given fields: ctx, postID, delta
func (_m *MockCache) IncrTotals(ctx context.Context, postID uint64, delta TotalsDelta) error {
	ret := _m.Called(ctx, postID, delta)

	if len(ret) == 0 {
		panic("no return value specified for IncrTotals")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, TotalsDelta) error); ok {
		r0 = rf(ctx, postID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_IncrTotals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrTotals'
type MockCache_IncrTotals_Call struct {
	*mock.Call
}

// IncrTotals is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint64
//   - delta TotalsDelta
func (_e *MockCache_Expecter) IncrTotals(ctx interface{}, postID interface{}, delta interface{}) *MockCache_IncrTotals_Call {
	return &MockCache_IncrTotals_Call{Call: _e.mock.On("IncrTotals", ctx, postID, delta)}
}

func (_c *MockCache_IncrTotals_Call) Run(run func(ctx context.Context, postID uint64, delta TotalsDelta)) *MockCache_IncrTotals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(TotalsDelta))
	})
	return _c
}

func (_c *MockCache_IncrTotals_Call) Return(_a0 error) *MockCache_IncrTotals_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_IncrTotals_Call) RunAndReturn(run func(context.Context, uint64, TotalsDelta) error) *MockCache_IncrTotals_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDirty provides a mock function with given fields: ctx, postID
func (_m *MockCache) MarkDirty(ctx context.Context, postID uint64) error {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for MarkDirty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_MarkDirty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDirty'
type MockCache_MarkDirty_Call struct {
	*mock.Call
}

// MarkDirty is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint64
func (_e *MockCache_Expecter) MarkDirty(ctx interface{}, postID interface{}) *MockCache_MarkDirty_Call {
	return &MockCache_MarkDirty_Call{Call: _e.mock.On("MarkDirty", ctx, postID)}
}

func (_c *MockCache_MarkDirty_Call) Run(run func(ctx context.Context, postID uint64)) *MockCache_MarkDirty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCache_MarkDirty_Call) Return(_a0 error) *MockCache_MarkDirty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_MarkDirty_Call) RunAndReturn(run func(context.Context, uint64) error) *MockCache_MarkDirty_Call {
	_c.Call.Return(run)
	return _c
}

// ResetDelta provides a mock function with given fields: ctx, postID
func (_m *MockCache) ResetDelta(ctx context.Context, postID uint64) error {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for ResetDelta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_ResetDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetDelta'
type MockCache_ResetDelta_Call struct {
	*mock.Call
}

// ResetDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint64
func (_e *MockCache_Expecter) ResetDelta(ctx interface{}, postID interface{}) *MockCache_ResetDelta_Call {
	return &MockCache_ResetDelta_Call{Call: _e.mock.On("ResetDelta", ctx, postID)}
}

func (_c *MockCache_ResetDelta_Call) Run(run func(ctx context.Context, postID uint64)) *MockCache_ResetDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCache_ResetDelta_Call) Return(_a0 error) *MockCache_ResetDelta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_ResetDelta_Call) RunAndReturn(run func(context.Context, uint64) error) *MockCache_ResetDelta_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastSyncedAt provides a mock function with given fields: ctx, ts
func (_m *MockCache) SetLastSyncedAt(ctx context.Context, ts string) error {
	ret := _m.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for SetLastSyncedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_SetLastSyncedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastSyncedAt'
type MockCache_SetLastSyncedAt_Call struct {
	*mock.Call
}

// SetLastSyncedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
func (_e *MockCache_Expecter) SetLastSyncedAt(ctx interface{}, ts interface{}) *MockCache_SetLastSyncedAt_Call {
	return &MockCache_SetLastSyncedAt_Call{Call: _e.mock.On("SetLastSyncedAt", ctx, ts)}
}

func (_c *MockCache_SetLastSyncedAt_Call) Run(run func(ctx context.Context, ts string)) *MockCache_SetLastSyncedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_SetLastSyncedAt_Call) Return(_a0 error) *MockCache_SetLastSyncedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetLastSyncedAt_Call) RunAndReturn(run func(context.Context, string) error) *MockCache_SetLastSyncedAt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
