// Code generated by mockery v2.53.5. DO NOT EDIT.

package analyticsService

import (
	context "context"

	models "github.com/sashapremium/events/internal/pb/models"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GetAuthorStats provides a mock function with given fields: ctx, authorID
func (_m *MockStorage) GetAuthorStats(ctx context.Context, authorID string) (*models.AuthorStatsModel, error) {
	ret := _m.Called(ctx, authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorStats")
	}

	var r0 *models.AuthorStatsModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.AuthorStatsModel, error)); ok {
		return rf(ctx, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.AuthorStatsModel); ok {
		r0 = rf(ctx, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AuthorStatsModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetAuthorStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorStats'
type MockStorage_GetAuthorStats_Call struct {
	*mock.Call
}

// GetAuthorStats is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
func (_e *MockStorage_Expecter) GetAuthorStats(ctx interface{}, authorID interface{}) *MockStorage_GetAuthorStats_Call {
	return &MockStorage_GetAuthorStats_Call{Call: _e.mock.On("GetAuthorStats", ctx, authorID)}
}

func (_c *MockStorage_GetAuthorStats_Call) Run(run func(ctx context.Context, authorID string)) *MockStorage_GetAuthorStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetAuthorStats_Call) Return(_a0 *models.AuthorStatsModel, _a1 error) *MockStorage_GetAuthorStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetAuthorStats_Call) RunAndReturn(run func(context.Context, string) (*models.AuthorStatsModel, error)) *MockStorage_GetAuthorStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostTotals provides a mock function with given fields: ctx, postID
func (_m *MockStorage) GetPostTotals(ctx context.Context, postID uint64) (PostTotals, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostTotals")
	}

	var r0 PostTotals
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (PostTotals, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) PostTotals); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(PostTotals)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetPostTotals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostTotals'
type MockStorage_GetPostTotals_Call struct {
	*mock.Call
}

// GetPostTotals is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint64
func (_e *MockStorage_Expecter) GetPostTotals(ctx interface{}, postID interface{}) *MockStorage_GetPostTotals_Call {
	return &MockStorage_GetPostTotals_Call{Call: _e.mock.On("GetPostTotals", ctx, postID)}
}

func (_c *MockStorage_GetPostTotals_Call) Run(run func(ctx context.Context, postID uint64)) *MockStorage_GetPostTotals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockStorage_GetPostTotals_Call) Return(_a0 PostTotals, _a1 error) *MockStorage_GetPostTotals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetPostTotals_Call) RunAndReturn(run func(context.Context, uint64) (PostTotals, error)) *MockStorage_GetPostTotals_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPostTotals provides a mock function with given fields: ctx, postID, delta
func (_m *MockStorage) UpsertPostTotals(ctx context.Context, postID uint64, delta TotalsDelta) error {
	ret := _m.Called(ctx, postID, delta)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPostTotals")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, TotalsDelta) error); ok {
		r0 = rf(ctx, postID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpsertPostTotals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPostTotals'
type MockStorage_UpsertPostTotals_Call struct {
	*mock.Call
}

// UpsertPostTotals is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint64
//   - delta TotalsDelta
func (_e *MockStorage_Expecter) UpsertPostTotals(ctx interface{}, postID interface{}, delta interface{}) *MockStorage_UpsertPostTotals_Call {
	return &MockStorage_UpsertPostTotals_Call{Call: _e.mock.On("UpsertPostTotals", ctx, postID, delta)}
}

func (_c *MockStorage_UpsertPostTotals_Call) Run(run func(ctx context.Context, postID uint64, delta TotalsDelta)) *MockStorage_UpsertPostTotals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(TotalsDelta))
	})
	return _c
}

func (_c *MockStorage_UpsertPostTotals_Call) Return(_a0 error) *MockStorage_UpsertPostTotals_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpsertPostTotals_Call) RunAndReturn(run func(context.Context, uint64, TotalsDelta) error) *MockStorage_UpsertPostTotals_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
