// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/sashapremium/events/events/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ProducerMock is an autogenerated mock type for the EventProducer type
type ProducerMock struct {
	mock.Mock
}

func (_m *ProducerMock) Send(ctx context.Context, key, value []byte) error {
	//TODO implement me
	panic("implement me")
}

func (_m *ProducerMock) Close() error {
	//TODO implement me
	panic("implement me")
}

// PublishEvent provides a mock function with given fields: ctx, event
func (_m *ProducerMock) PublishEvent(ctx context.Context, event *events.ContentEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *events.ContentEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProducerMock creates a new instance of ProducerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProducerMock {
	mock := &ProducerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
