// Code generated by mockery v2.53.5. DO NOT EDIT.
package mocks

import (
	context "context"

	events "github.com/sashapremium/events/events/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// StorageMock is a mock type for the eventsService.Storage interface.
type StorageMock struct {
	mock.Mock
}

// InsertEvents provides a mock function with given fields: ctx, _a1
func (_m *StorageMock) InsertEvents(ctx context.Context, _a1 []*events.ContentEvent) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*events.ContentEvent) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPost provides a mock function with given fields: ctx, id
func (_m *StorageMock) GetPost(ctx context.Context, id uint64) (*events.PostInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPost")
	}

	var r0 *events.PostInfo
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *events.PostInfo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*events.PostInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPostAuthorID provides a mock function with given fields: ctx, postID
func (_m *StorageMock) GetPostAuthorID(ctx context.Context, postID uint64) (uint64, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostAuthorID")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = rf(ctx, postID)
	} else {
		// ret.Get(0) может быть int/uint64 — приводим безопасно
		switch v := ret.Get(0).(type) {
		case uint64:
			r0 = v
		case int:
			r0 = uint64(v)
		case int64:
			r0 = uint64(v)
		case uint:
			r0 = uint64(v)
		default:
			r0 = 0
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func NewStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageMock {
	m := &StorageMock{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}
