// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/sashapremium/events/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// StorageMock is an autogenerated mock type for the Storage type
type StorageMock struct {
	mock.Mock
}

// InsertEvents provides a mock function with given fields: ctx, _a1
func (_m *StorageMock) InsertEvents(ctx context.Context, _a1 []*events.ContentEvent) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*events.ContentEvent) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorageMock creates a new instance of StorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageMock {
	mock := &StorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
