// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analytics_api/analytics.proto

package analytics_api

import (
	models "github.com/sashapremium/events/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Fresh         bool                   `protobuf:"varint,2,opt,name=fresh,proto3" json:"fresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsRequest) Reset() {
	*x = GetPostStatsRequest{}
	mi := &file_analytics_api_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsRequest) ProtoMessage() {}

func (x *GetPostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_api_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPostStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_api_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostStatsRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostStatsRequest) GetFresh() bool {
	if x != nil {
		return x.Fresh
	}
	return false
}

type GetPostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *models.PostStatsModel `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsResponse) Reset() {
	*x = GetPostStatsResponse{}
	mi := &file_analytics_api_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsResponse) ProtoMessage() {}

func (x *GetPostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_api_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsResponse.ProtoReflect.Descriptor instead.
func (*GetPostStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_api_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostStatsResponse) GetStats() *models.PostStatsModel {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetTopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopRequest) Reset() {
	*x = GetTopRequest{}
	mi := &file_analytics_api_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopRequest) ProtoMessage() {}

func (x *GetTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_api_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopRequest.ProtoReflect.Descriptor instead.
func (*GetTopRequest) Descriptor() ([]byte, []int) {
	return file_analytics_api_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetTopRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           *models.TopModel       `protobuf:"bytes,1,opt,name=top,proto3" json:"top,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopResponse) Reset() {
	*x = GetTopResponse{}
	mi := &file_analytics_api_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopResponse) ProtoMessage() {}

func (x *GetTopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_api_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopResponse.ProtoReflect.Descriptor instead.
func (*GetTopResponse) Descriptor() ([]byte, []int) {
	return file_analytics_api_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopResponse) GetTop() *models.TopModel {
	if x != nil {
		return x.Top
	}
	return nil
}

type GetAuthorStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorStatsRequest) Reset() {
	*x = GetAuthorStatsRequest{}
	mi := &file_analytics_api_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorStatsRequest) ProtoMessage() {}

func (x *GetAuthorStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_api_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorStatsRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_api_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthorStatsRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type GetAuthorStatsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Stats         *models.AuthorStatsModel `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorStatsResponse) Reset() {
	*x = GetAuthorStatsResponse{}
	mi := &file_analytics_api_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorStatsResponse) ProtoMessage() {}

func (x *GetAuthorStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_api_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorStatsResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_api_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthorStatsResponse) GetStats() *models.AuthorStatsModel {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_analytics_api_analytics_proto protoreflect.FileDescriptor

const file_analytics_api_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1danalytics_api/analytics.proto\x12\x14analytics.service.v1\x1a\x1cmodels/analytics_model.proto\x1a\x1cgoogle/api/annotations.proto\"D\n" +
	"\x13GetPostStatsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x14\n" +
	"\x05fresh\x18\x02 \x01(\bR\x05fresh\"Q\n" +
	"\x14GetPostStatsResponse\x129\n" +
	"\x05stats\x18\x01 \x01(\v2#.analytics.models.v1.PostStatsModelR\x05stats\"=\n" +
	"\rGetTopRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"A\n" +
	"\x0eGetTopResponse\x12/\n" +
	"\x03top\x18\x01 \x01(\v2\x1d.analytics.models.v1.TopModelR\x03top\"4\n" +
	"\x15GetAuthorStatsRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\"U\n" +
	"\x16GetAuthorStatsResponse\x12;\n" +
	"\x05stats\x18\x01 \x01(\v2%.analytics.models.v1.AuthorStatsModelR\x05stats2\xb4\x03\n" +
	"\x10AnalyticsService\x12\x8f\x01\n" +
	"\fGetPostStats\x12).analytics.service.v1.GetPostStatsRequest\x1a*.analytics.service.v1.GetPostStatsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/analytics/post/{post_id}\x12r\n" +
	"\x06GetTop\x12#.analytics.service.v1.GetTopRequest\x1a$.analytics.service.v1.GetTopResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/analytics/top\x12\x99\x01\n" +
	"\x0eGetAuthorStats\x12+.analytics.service.v1.GetAuthorStatsRequest\x1a,.analytics.service.v1.GetAuthorStatsResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/analytics/author/{author_id}BHZFgithub.com/sashapremium/events/internal/pb/analytics_api;analytics_apib\x06proto3"

var (
	file_analytics_api_analytics_proto_rawDescOnce sync.Once
	file_analytics_api_analytics_proto_rawDescData []byte
)

func file_analytics_api_analytics_proto_rawDescGZIP() []byte {
	file_analytics_api_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_api_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_api_analytics_proto_rawDesc), len(file_analytics_api_analytics_proto_rawDesc)))
	})
	return file_analytics_api_analytics_proto_rawDescData
}

var file_analytics_api_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_analytics_api_analytics_proto_goTypes = []any{
	(*GetPostStatsRequest)(nil),     // 0: analytics.service.v1.GetPostStatsRequest
	(*GetPostStatsResponse)(nil),    // 1: analytics.service.v1.GetPostStatsResponse
	(*GetTopRequest)(nil),           // 2: analytics.service.v1.GetTopRequest
	(*GetTopResponse)(nil),          // 3: analytics.service.v1.GetTopResponse
	(*GetAuthorStatsRequest)(nil),   // 4: analytics.service.v1.GetAuthorStatsRequest
	(*GetAuthorStatsResponse)(nil),  // 5: analytics.service.v1.GetAuthorStatsResponse
	(*models.PostStatsModel)(nil),   // 6: analytics.models.v1.PostStatsModel
	(*models.TopModel)(nil),         // 7: analytics.models.v1.TopModel
	(*models.AuthorStatsModel)(nil), // 8: analytics.models.v1.AuthorStatsModel
}
var file_analytics_api_analytics_proto_depIdxs = []int32{
	6, // 0: analytics.service.v1.GetPostStatsResponse.stats:type_name -> analytics.models.v1.PostStatsModel
	7, // 1: analytics.service.v1.GetTopResponse.top:type_name -> analytics.models.v1.TopModel
	8, // 2: analytics.service.v1.GetAuthorStatsResponse.stats:type_name -> analytics.models.v1.AuthorStatsModel
	0, // 3: analytics.service.v1.AnalyticsService.GetPostStats:input_type -> analytics.service.v1.GetPostStatsRequest
	2, // 4: analytics.service.v1.AnalyticsService.GetTop:input_type -> analytics.service.v1.GetTopRequest
	4, // 5: analytics.service.v1.AnalyticsService.GetAuthorStats:input_type -> analytics.service.v1.GetAuthorStatsRequest
	1, // 6: analytics.service.v1.AnalyticsService.GetPostStats:output_type -> analytics.service.v1.GetPostStatsResponse
	3, // 7: analytics.service.v1.AnalyticsService.GetTop:output_type -> analytics.service.v1.GetTopResponse
	5, // 8: analytics.service.v1.AnalyticsService.GetAuthorStats:output_type -> analytics.service.v1.GetAuthorStatsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_analytics_api_analytics_proto_init() }
func file_analytics_api_analytics_proto_init() {
	if File_analytics_api_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_api_analytics_proto_rawDesc), len(file_analytics_api_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_api_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_api_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_api_analytics_proto_msgTypes,
	}.Build()
	File_analytics_api_analytics_proto = out.File
	file_analytics_api_analytics_proto_goTypes = nil
	file_analytics_api_analytics_proto_depIdxs = nil
}
