// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: models/analytics_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Итоговые агрегаты по посту
type TotalsModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalViews    int64                  `protobuf:"varint,1,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalLikes    int64                  `protobuf:"varint,2,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	TotalComments int64                  `protobuf:"varint,3,opt,name=total_comments,json=totalComments,proto3" json:"total_comments,omitempty"`
	TotalReposts  int64                  `protobuf:"varint,4,opt,name=total_reposts,json=totalReposts,proto3" json:"total_reposts,omitempty"`
	UniqueUsers   int64                  `protobuf:"varint,5,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalsModel) Reset() {
	*x = TotalsModel{}
	mi := &file_models_analytics_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalsModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalsModel) ProtoMessage() {}

func (x *TotalsModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_analytics_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalsModel.ProtoReflect.Descriptor instead.
func (*TotalsModel) Descriptor() ([]byte, []int) {
	return file_models_analytics_model_proto_rawDescGZIP(), []int{0}
}

func (x *TotalsModel) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *TotalsModel) GetTotalLikes() int64 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

func (x *TotalsModel) GetTotalComments() int64 {
	if x != nil {
		return x.TotalComments
	}
	return 0
}

func (x *TotalsModel) GetTotalReposts() int64 {
	if x != nil {
		return x.TotalReposts
	}
	return 0
}

func (x *TotalsModel) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

// Свежий хвост из Redis
type FreshTailModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         int64                  `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int64                  `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments      int64                  `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
	Reposts       int64                  `protobuf:"varint,4,opt,name=reposts,proto3" json:"reposts,omitempty"`
	UniqueUsers   int64                  `protobuf:"varint,5,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreshTailModel) Reset() {
	*x = FreshTailModel{}
	mi := &file_models_analytics_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreshTailModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreshTailModel) ProtoMessage() {}

func (x *FreshTailModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_analytics_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreshTailModel.ProtoReflect.Descriptor instead.
func (*FreshTailModel) Descriptor() ([]byte, []int) {
	return file_models_analytics_model_proto_rawDescGZIP(), []int{1}
}

func (x *FreshTailModel) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *FreshTailModel) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *FreshTailModel) GetComments() int64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *FreshTailModel) GetReposts() int64 {
	if x != nil {
		return x.Reposts
	}
	return 0
}

func (x *FreshTailModel) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

type PostStatsModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Totals        *TotalsModel           `protobuf:"bytes,2,opt,name=totals,proto3" json:"totals,omitempty"`
	FreshTail     *FreshTailModel        `protobuf:"bytes,3,opt,name=fresh_tail,json=freshTail,proto3" json:"fresh_tail,omitempty"`
	LastSyncedAt  string                 `protobuf:"bytes,4,opt,name=last_synced_at,json=lastSyncedAt,proto3" json:"last_synced_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsModel) Reset() {
	*x = PostStatsModel{}
	mi := &file_models_analytics_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsModel) ProtoMessage() {}

func (x *PostStatsModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_analytics_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsModel.ProtoReflect.Descriptor instead.
func (*PostStatsModel) Descriptor() ([]byte, []int) {
	return file_models_analytics_model_proto_rawDescGZIP(), []int{2}
}

func (x *PostStatsModel) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostStatsModel) GetTotals() *TotalsModel {
	if x != nil {
		return x.Totals
	}
	return nil
}

func (x *PostStatsModel) GetFreshTail() *FreshTailModel {
	if x != nil {
		return x.FreshTail
	}
	return nil
}

func (x *PostStatsModel) GetLastSyncedAt() string {
	if x != nil {
		return x.LastSyncedAt
	}
	return ""
}

// Элемент топа
type TopItemModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopItemModel) Reset() {
	*x = TopItemModel{}
	mi := &file_models_analytics_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopItemModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopItemModel) ProtoMessage() {}

func (x *TopItemModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_analytics_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopItemModel.ProtoReflect.Descriptor instead.
func (*TopItemModel) Descriptor() ([]byte, []int) {
	return file_models_analytics_model_proto_rawDescGZIP(), []int{3}
}

func (x *TopItemModel) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *TopItemModel) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TopModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"` // просмотр, комментарии, лайки
	Items         []*TopItemModel        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopModel) Reset() {
	*x = TopModel{}
	mi := &file_models_analytics_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopModel) ProtoMessage() {}

func (x *TopModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_analytics_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopModel.ProtoReflect.Descriptor instead.
func (*TopModel) Descriptor() ([]byte, []int) {
	return file_models_analytics_model_proto_rawDescGZIP(), []int{4}
}

func (x *TopModel) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TopModel) GetItems() []*TopItemModel {
	if x != nil {
		return x.Items
	}
	return nil
}

type AuthorStatsModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Posts         uint64                 `protobuf:"varint,2,opt,name=posts,proto3" json:"posts,omitempty"`
	TotalViews    int64                  `protobuf:"varint,3,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalLikes    int64                  `protobuf:"varint,4,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	TotalComments int64                  `protobuf:"varint,5,opt,name=total_comments,json=totalComments,proto3" json:"total_comments,omitempty"`
	TotalReposts  int64                  `protobuf:"varint,6,opt,name=total_reposts,json=totalReposts,proto3" json:"total_reposts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorStatsModel) Reset() {
	*x = AuthorStatsModel{}
	mi := &file_models_analytics_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorStatsModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorStatsModel) ProtoMessage() {}

func (x *AuthorStatsModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_analytics_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorStatsModel.ProtoReflect.Descriptor instead.
func (*AuthorStatsModel) Descriptor() ([]byte, []int) {
	return file_models_analytics_model_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorStatsModel) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *AuthorStatsModel) GetPosts() uint64 {
	if x != nil {
		return x.Posts
	}
	return 0
}

func (x *AuthorStatsModel) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *AuthorStatsModel) GetTotalLikes() int64 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

func (x *AuthorStatsModel) GetTotalComments() int64 {
	if x != nil {
		return x.TotalComments
	}
	return 0
}

func (x *AuthorStatsModel) GetTotalReposts() int64 {
	if x != nil {
		return x.TotalReposts
	}
	return 0
}

var File_models_analytics_model_proto protoreflect.FileDescriptor

const file_models_analytics_model_proto_rawDesc = "" +
	"\n" +
	"\x1cmodels/analytics_model.proto\x12\x13analytics.models.v1\"\xbe\x01\n" +
	"\vTotalsModel\x12\x1f\n" +
	"\vtotal_views\x18\x01 \x01(\x03R\n" +
	"totalViews\x12\x1f\n" +
	"\vtotal_likes\x18\x02 \x01(\x03R\n" +
	"totalLikes\x12%\n" +
	"\x0etotal_comments\x18\x03 \x01(\x03R\rtotalComments\x12#\n" +
	"\rtotal_reposts\x18\x04 \x01(\x03R\ftotalReposts\x12!\n" +
	"\funique_users\x18\x05 \x01(\x03R\vuniqueUsers\"\x95\x01\n" +
	"\x0eFreshTailModel\x12\x14\n" +
	"\x05views\x18\x01 \x01(\x03R\x05views\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\x03R\x05likes\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\x03R\bcomments\x12\x18\n" +
	"\areposts\x18\x04 \x01(\x03R\areposts\x12!\n" +
	"\funique_users\x18\x05 \x01(\x03R\vuniqueUsers\"\xcd\x01\n" +
	"\x0ePostStatsModel\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x128\n" +
	"\x06totals\x18\x02 \x01(\v2 .analytics.models.v1.TotalsModelR\x06totals\x12B\n" +
	"\n" +
	"fresh_tail\x18\x03 \x01(\v2#.analytics.models.v1.FreshTailModelR\tfreshTail\x12$\n" +
	"\x0elast_synced_at\x18\x04 \x01(\tR\flastSyncedAt\"=\n" +
	"\fTopItemModel\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"[\n" +
	"\bTopModel\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.analytics.models.v1.TopItemModelR\x05items\"\xd3\x01\n" +
	"\x10AuthorStatsModel\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05posts\x18\x02 \x01(\x04R\x05posts\x12\x1f\n" +
	"\vtotal_views\x18\x03 \x01(\x03R\n" +
	"totalViews\x12\x1f\n" +
	"\vtotal_likes\x18\x04 \x01(\x03R\n" +
	"totalLikes\x12%\n" +
	"\x0etotal_comments\x18\x05 \x01(\x03R\rtotalComments\x12#\n" +
	"\rtotal_reposts\x18\x06 \x01(\x03R\ftotalRepostsBDZBgithub.com/sashapremium/events/analytics/internal/pb/models;modelsb\x06proto3"

var (
	file_models_analytics_model_proto_rawDescOnce sync.Once
	file_models_analytics_model_proto_rawDescData []byte
)

func file_models_analytics_model_proto_rawDescGZIP() []byte {
	file_models_analytics_model_proto_rawDescOnce.Do(func() {
		file_models_analytics_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_analytics_model_proto_rawDesc), len(file_models_analytics_model_proto_rawDesc)))
	})
	return file_models_analytics_model_proto_rawDescData
}

var file_models_analytics_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_models_analytics_model_proto_goTypes = []any{
	(*TotalsModel)(nil),      // 0: analytics.models.v1.TotalsModel
	(*FreshTailModel)(nil),   // 1: analytics.models.v1.FreshTailModel
	(*PostStatsModel)(nil),   // 2: analytics.models.v1.PostStatsModel
	(*TopItemModel)(nil),     // 3: analytics.models.v1.TopItemModel
	(*TopModel)(nil),         // 4: analytics.models.v1.TopModel
	(*AuthorStatsModel)(nil), // 5: analytics.models.v1.AuthorStatsModel
}
var file_models_analytics_model_proto_depIdxs = []int32{
	0, // 0: analytics.models.v1.PostStatsModel.totals:type_name -> analytics.models.v1.TotalsModel
	1, // 1: analytics.models.v1.PostStatsModel.fresh_tail:type_name -> analytics.models.v1.FreshTailModel
	3, // 2: analytics.models.v1.TopModel.items:type_name -> analytics.models.v1.TopItemModel
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_models_analytics_model_proto_init() }
func file_models_analytics_model_proto_init() {
	if File_models_analytics_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_analytics_model_proto_rawDesc), len(file_models_analytics_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_analytics_model_proto_goTypes,
		DependencyIndexes: file_models_analytics_model_proto_depIdxs,
		MessageInfos:      file_models_analytics_model_proto_msgTypes,
	}.Build()
	File_models_analytics_model_proto = out.File
	file_models_analytics_model_proto_goTypes = nil
	file_models_analytics_model_proto_depIdxs = nil
}
